# Generated by Django 4.2.1 on 2023-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_botsettings_site_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Регистрация'), (1, 'Первый депозит'), (2, 'Депозит')], default=0, verbose_name='Вид события')),
                ('event_id', models.CharField(default='', max_length=128, verbose_name='Event Id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('amount', models.FloatField(blank=True, verbose_name='Сумма')),
                ('country', models.CharField(blank=True, default='', max_length=128, verbose_name='Страна')),
                ('user_id', models.CharField(default='', max_length=128, verbose_name='User Id')),
                ('sub1', models.CharField(default='', max_length=128, verbose_name='Sub1')),
            ],
            options={
                'verbose_name': 'PostBack событие',
                'verbose_name_plural': 'PostBack события',
            },
        ),
    ]
