# Generated by Django 4.2.1 on 2023-06-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_postbackevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbackevent',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
