# Generated by Django 4.2.1 on 2023-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='users',
            field=models.ManyToManyField(blank=True, to='backend.telegramuser', verbose_name='Адресаты'),
        ),
    ]
