# Generated by Django 4.2.1 on 2023-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_botmessage_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Статус бота',
            },
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Если адресата оставить пустым, сообщение уйдет всем пользователям бота', to='backend.telegramuser', verbose_name='Адресаты'),
        ),
    ]
