# Generated by Django 4.2.1 on 2023-06-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_link', models.CharField(default='', max_length=128, verbose_name='Ссылка по поддержку')),
                ('bot_token', models.TextField(default='', verbose_name='Токен бота')),
            ],
            options={
                'verbose_name': 'Настройки бота',
            },
        ),
    ]
