# Generated by Django 4.2.1 on 2023-06-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_boterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='site_link',
            field=models.CharField(default='', max_length=128, verbose_name='Ссылка на сайт'),
        ),
    ]
