# Generated by Django 4.2.1 on 2023-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_postbackevent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='channel_link',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Ссылка на канал'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='refill_link',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Ссылка для пополнения'),
        ),
    ]
