# Generated by Django 4.2.1 on 2023-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_botmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(default='', max_length=64, verbose_name='Telegram Id')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Имя')),
                ('username', models.CharField(default='', help_text='t.me/@<имя пользователя>', max_length=256, verbose_name='Имя пользователя Telegram')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
            },
        ),
    ]
