# Generated by Django 4.2.1 on 2023-06-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_bottext'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.SlugField(max_length=128, unique=True, verbose_name='Идентификатор кнопки')),
                ('text', models.TextField(max_length=128, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Кнопка бота',
                'verbose_name_plural': 'Кнопки бота',
            },
        ),
    ]
